import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <a href="/">Home</a>
          <a href="/transaction-history">Transaction History</a>
          <a href="/budgets">Budgets</a>
          <a href="/trends">Trends</a>
        </nav>
        {children}
        <div className="global-footer"></div>
      </body>
    </html>
  );
}
